package Presentation;

/**
*
* @author niapa
*/
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import Persistence.DbUtils;
import Persistence.Employee;

import java.sql.*;
import java.security.*;

public class addEmployeeGUI extends javax.swing.JFrame {

    /**
     * Creates new form addEmployeeGUI
     */

    private Connection conn;
    private Statement stmt;
    private ResultSet rSet;
    private PreparedStatement ps;
    private ArrayList<Employee> tableList = new ArrayList<>();
    private String[] columnNames = { "EmployeeID", "First_Name", "Last_Name", "Age", "Gender", "Username" };
    DefaultTableModel tableModel = new DefaultTableModel(columnNames, 0);
    JOptionPane jOptionPane = new JOptionPane();
    int idCount = 0;

    public addEmployeeGUI() {
        initComponents();
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost/comp2171", "root", "");
            stmt = conn.createStatement();
            // tableList = getData();
            // loadTable(tableList);
            table_load();
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        infoLabel = new javax.swing.JLabel();
        formPanel = new javax.swing.JPanel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        ageTextField = new javax.swing.JTextField();
        usernameTextField = new javax.swing.JTextField();
        passwordTextField = new javax.swing.JTextField();
        genderComboBox = new javax.swing.JComboBox<>();
        saveButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        tableScrollPane = new javax.swing.JScrollPane();
        employeeTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        infoLabel.setFont(new java.awt.Font("Georgia", 3, 36)); // NOI18N
        infoLabel.setForeground(new java.awt.Color(0, 51, 204));
        infoLabel.setText("Employee Information");

        formPanel.setBackground(new java.awt.Color(255, 255, 255));
        formPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204)));
        formPanel.setForeground(new java.awt.Color(0, 51, 204));

        firstNameLabel.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        firstNameLabel.setForeground(new java.awt.Color(0, 51, 204));
        firstNameLabel.setText("First Name");

        lastNameLabel.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        lastNameLabel.setForeground(new java.awt.Color(0, 51, 204));
        lastNameLabel.setText("Last Name");

        ageLabel.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        ageLabel.setForeground(new java.awt.Color(0, 51, 204));
        ageLabel.setText("Age");

        genderLabel.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        genderLabel.setForeground(new java.awt.Color(0, 51, 204));
        genderLabel.setText("Gender");

        usernameLabel.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(0, 51, 204));
        usernameLabel.setText("Username");

        passwordLabel.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(0, 51, 204));
        passwordLabel.setText("Password");

        firstNameTextField
                .setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204)));

        lastNameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204)));
        lastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextFieldActionPerformed(evt);
            }
        });

        ageTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204)));

        usernameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204)));

        passwordTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204)));

        genderComboBox.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        genderComboBox.setForeground(new java.awt.Color(0, 51, 204));
        genderComboBox.setModel(
                new javax.swing.DefaultComboBoxModel<>(
                        new String[] { "Select a gender ......", "Female", "Male" }));
        genderComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204)));

        javax.swing.GroupLayout formPanelLayout = new javax.swing.GroupLayout(formPanel);
        formPanel.setLayout(formPanelLayout);
        formPanelLayout.setHorizontalGroup(
                formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(formPanelLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(formPanelLayout
                                        .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                false)
                                        .addComponent(firstNameLabel,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                71,
                                                Short.MAX_VALUE)
                                        .addComponent(lastNameLabel,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addComponent(ageLabel,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addComponent(genderLabel,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addComponent(usernameLabel,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addComponent(passwordLabel,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE))
                                .addGap(39, 39, 39)
                                .addGroup(formPanelLayout
                                        .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                false)
                                        .addComponent(firstNameTextField)
                                        .addComponent(lastNameTextField)
                                        .addComponent(ageTextField)
                                        .addComponent(usernameTextField)
                                        .addComponent(passwordTextField)
                                        .addComponent(genderComboBox, 0, 202,
                                                Short.MAX_VALUE))
                                .addContainerGap(46, Short.MAX_VALUE)));
        formPanelLayout.setVerticalGroup(
                formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(formPanelLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(formPanelLayout
                                        .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(firstNameLabel,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                37,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(firstNameTextField,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                37,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(
                                        formPanelLayout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(lastNameLabel,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        37,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lastNameTextField,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        37,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(formPanelLayout
                                        .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                false)
                                        .addComponent(ageLabel,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addComponent(ageTextField,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                37,
                                                Short.MAX_VALUE))
                                .addGap(34, 34, 34)
                                .addGroup(
                                        formPanelLayout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(genderLabel,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        37,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(genderComboBox,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        37,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(
                                        formPanelLayout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(usernameLabel,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        37,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(usernameTextField,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        37,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(formPanelLayout
                                        .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                false)
                                        .addComponent(passwordLabel,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addComponent(passwordTextField,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                37,
                                                Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)));

        saveButton.setBackground(new java.awt.Color(0, 51, 204));
        saveButton.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setText("SAVE");
        saveButton.setPreferredSize(new java.awt.Dimension(72, 41));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    saveButtonActionPerformed(evt);
                } catch (ClassNotFoundException e) {
                    e.printStackTrace();
                } catch (NoSuchAlgorithmException e) {
                    e.printStackTrace();
                    e.printStackTrace();
                }
            }
        });

        editButton.setBackground(new java.awt.Color(0, 51, 204));
        editButton.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        editButton.setForeground(new java.awt.Color(255, 255, 255));
        editButton.setText("EDIT");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    editButtonActionPerformed(evt);
                } catch (ClassNotFoundException e) {
                    e.printStackTrace();
                } catch (NoSuchAlgorithmException e) {
                    e.printStackTrace();
                    e.printStackTrace();
                }
            }
        });

        deleteButton.setBackground(new java.awt.Color(0, 51, 204));
        deleteButton.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("DELETE");
        deleteButton.setMaximumSize(new java.awt.Dimension(72, 24));
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    deleteButtonActionPerformed(evt);
                } catch (ClassNotFoundException e) {
                    e.printStackTrace();
                } catch (NoSuchAlgorithmException e) {
                    e.printStackTrace();
                    e.printStackTrace();
                }
            }
        });

        tableScrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204)));
        employeeTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null }
                },
                new String[] {
                        "EmployeeID", "First_Name", "Last_Name", "Age", "Gender", "Username"
                }) {
            Class[] types = new Class[] {
                    java.lang.Integer.class, java.lang.String.class, java.lang.String.class,
                    java.lang.Integer.class,
                    java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        tableScrollPane.setViewportView(employeeTable);

        homeButton.setBackground(new java.awt.Color(0, 51, 204));
        homeButton.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        homeButton.setForeground(new java.awt.Color(255, 255, 255));
        homeButton.setText("HOME");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addComponent(formPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(tableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        651, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(60, 60, 60)
                                                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(64, 64, 64)
                                                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(235, 235, 235)
                                                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(71, 71, 71)
                                                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                                .addGap(277, 277, 277)
                                .addComponent(infoLabel)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(infoLabel)
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(formPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 487,
                                                Short.MAX_VALUE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)));

        pack();
    }// </editor-fold>

    private void lastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt)
            throws ClassNotFoundException, NoSuchAlgorithmException {
        String firstName, lastName, gender, username, password;
        int age;

        firstName = firstNameTextField.getText();
        lastName = lastNameTextField.getText();
        age = Integer.parseInt(ageTextField.getText());
        gender = genderComboBox.getSelectedItem().toString();
        username = usernameTextField.getText();
        String salt = getSalt();
        password = hashPassword(passwordTextField.getText(), salt);

        try {
            // connection is the name of the database class in connection.java
            Connection conn;
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/comp2171", "root", "");
            // stmt = conn.createStatement();
            ps = conn.prepareStatement("INSERT INTO Employee" +
                    "(First_Name, Last_Name, Age, Gender, Username, Password)" +
                    "VALUES(?,?,?,?,?,?)");
            ps.setString(1, firstName);
            ps.setString(2, lastName);
            ps.setInt(3, age);
            ps.setString(4, gender);
            ps.setString(5, username);
            ps.setString(6, password);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,
                    String.format("%s %s was added to database!!", firstName, lastName));
            // tableList = getData();
            // loadTable(getData());
            table_load();
            firstNameTextField.setText("");
            lastNameTextField.setText("");
            ageTextField.setText("");
            genderComboBox.setSelectedIndex(0);
            usernameTextField.setText("");
            passwordTextField.setText("");
        } catch (SQLException e) {
            System.out.println("Error Connecting to Database!!!");
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public ArrayList<Employee> getData() throws SQLException {
        rSet = stmt.executeQuery("SELECT * FROM Employee");
        ArrayList<Employee> empList = new ArrayList<>();
        while (rSet.next()) {
            int EmployeeID = rSet.getInt("EmployeeID");
            String firstName = rSet.getString("First_Name");
            String lastName = rSet.getString("Last_Name");
            int age = rSet.getInt("Age");
            String gender = rSet.getString("Gender");
            String username = rSet.getString("Username");
            String password = rSet.getString("Password");

            Employee employee = new Employee(EmployeeID, firstName, lastName, age, gender, username,
                    password);
            empList.add(employee);
        }
        return empList;
    }

    public void loadTable(ArrayList<Employee> aList) {
        if (aList.size() > 0) {
            for (Employee emp : aList) {
                String[] employee = { String.valueOf(emp.getId()), emp.getFirstName(),
                        emp.getLastName(), String.valueOf(emp.getAge()), emp.getGender(),
                        emp.getUsername() };
                employeeTable.setModel(tableModel);
                tableModel.addRow(employee);
            }
        }
    }

    public void table_load() {
        try {
            ps = conn.prepareStatement("SELECT * FROM Employee");
            rSet = ps.executeQuery();
            employeeTable.setModel(DbUtils.resultSetToTableModel(rSet));
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private static String hashPassword(String passwordToHash, String salt) {
        String generatedPassword = null;
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-512");
            md.update(salt.getBytes());
            byte[] bytes = md.digest(passwordToHash.getBytes());
            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < bytes.length; i++) {
                sb.append(Integer.toString((bytes[i] & 0xff) + 0x100, 16)
                        .substring(1));
            }
            generatedPassword = sb.toString();
        } catch (NoSuchAlgorithmException e) {
            e.printStackTrace();
        }
        return generatedPassword;
    }

    private static String getSalt() throws NoSuchAlgorithmException {
        SecureRandom sr = SecureRandom.getInstance("SHA1PRNG");
        byte[] salt = new byte[16];
        sr.nextBytes(salt);
        return salt.toString();
    }

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt)
            throws ClassNotFoundException, NoSuchAlgorithmException {
        String firstName, lastName, gender, username, password;
        int age;

        int row = employeeTable.getSelectedRow();
        int column = employeeTable.getSelectedColumn();
        String data = employeeTable.getValueAt(row, column).toString();
        System.out.println(data);

        firstName = firstNameTextField.getText();
        lastName = lastNameTextField.getText();
        age = Integer.parseInt(ageTextField.getText());
        gender = genderComboBox.getSelectedItem().toString();
        username = usernameTextField.getText();
        String salt = getSalt();
        password = hashPassword(passwordTextField.getText(), salt);
        int EmployeeID = Integer.parseInt(data);
        Employee emp = new Employee(EmployeeID, firstName, lastName, age, gender, username, password);

        try {
            // connection is the name of the database class in connection.java
            // DB_Connect db = new DB_Connect();
            Connection conn;
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/comp2171", "root", "");
            ps = conn.prepareStatement(
                    "UPDATE Employee SET First_Name=?, Last_Name=?, Age=?, Gender=?, Username=?, Password=? WHERE EmployeeID=?");
            ps.setString(1, firstName);
            ps.setString(2, lastName);
            ps.setInt(3, age);
            ps.setString(4, gender);
            ps.setString(5, username);
            ps.setString(6, password);
            ps.setInt(7, EmployeeID);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,
                    String.format("%s %s information was updated in database!!", firstName, lastName));
            // tableList = getData();
            // loadTable(getData());
            table_load();
            firstNameTextField.setText("");
            lastNameTextField.setText("");
            ageTextField.setText("");
            genderComboBox.setSelectedIndex(0);
            usernameTextField.setText("");
            passwordTextField.setText("");
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
        }
    }

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt)
            throws ClassNotFoundException, NoSuchAlgorithmException {
        // String EmployeeID;
        int row = employeeTable.getSelectedRow();
        int column = employeeTable.getSelectedColumn();
        String data = employeeTable.getValueAt(row, column).toString();
        int EmployeeID = Integer.parseInt(data);

        try {
            String ObjButtons[] = { "Yes", "No" };
            int PromptResult = JOptionPane.showOptionDialog(null, "Are you sure you want to delete record?",
                    "Employee Information System", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null,
                    ObjButtons, ObjButtons[1]);
            if (PromptResult == JOptionPane.YES_OPTION) {
                Connection conn;
                Class.forName("com.mysql.cj.jdbc.Driver");
                conn = DriverManager.getConnection("jdbc:mysql://localhost/comp2171", "root", "");
                ps = conn.prepareStatement("DELETE FROM Employee WHERE EmployeeID = ?");
                ps.setInt(1, EmployeeID);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Record information was deleted from database!!");
                table_load();
            }
            if (PromptResult == JOptionPane.NO_OPTION) {
                JOptionPane.getRootFrame().dispose();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         *
         */
        HashMap<String, String> loginInfo = new HashMap<String, String>();
        loginInfo.put("ADMIN", "admin");
        loginInfo.put("LisaG", "LisaG");
        loginInfo.put("AmandaL", "AmandaL");
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addEmployeeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addEmployeeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addEmployeeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addEmployeeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage(loginInfo);
                // new addEmployeeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JTable employeeTable;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JPanel formPanel;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JButton saveButton;
    private javax.swing.JScrollPane tableScrollPane;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration
}
